### ISSUE TITLE
When you consider releasing the data?

### ISSUE THREAD

**Issue by weichow23** [poppyxu/InsightEdit#1]
Very good work! I would like to ask when you consider releasing the data?

**Comment by poppyxu** [comment]
Thank u for the attention. :)
We're preparing...

**Comment by xduzhangjiayu** [comment]
Hi author,
May I ask which base SD model you have used for training InsightEdit model, and will the train code open source? @poppyxu 
Thanks so much!

**Comment by poppyxu** [comment]
Heyyyy, we use SD1.5 as our base model. Before we release the corresponding materials, I highly recommend to check the source code of SmartEdit, our work is building upon this amazing work! :)

**Comment by xduzhangjiayu** [comment]
> Heyyyy, we use SD1.5 as our base model. Before we release the corresponding materials, I highly recommend to check the source code of SmartEdit, our work is building upon this amazing work! :)

Thanks a lot!
